package com.lbins.myapp.entity;

import com.lbins.myapp.db.DaoSession;
import com.lbins.myapp.db.ShoppingCartDao;
import de.greenrobot.dao.DaoException;

import java.io.Serializable;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table SHOPPING_CART.
 */
public class ShoppingCart implements Serializable{

    /** Not-null value. */
    private String cartid;
    /** Not-null value. */
    private String goods_id;
    private String emp_id;
    private String manager_id;
    private String emp_name;
    private String emp_cover;
    private String goods_name;
    private String goods_cover;
    private String sell_price;
    private String marketPrice;
    private String goods_count;
    private String dateline;
    private String is_zhiying;
    private String is_select;
    private String pv_prices;
    private String is_zhekou;
    private String zhekou_number;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ShoppingCartDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ShoppingCart() {
    }

    public ShoppingCart(String cartid) {
        this.cartid = cartid;
    }

    public ShoppingCart(String cartid, String goods_id, String emp_id, String manager_id, String emp_name, String emp_cover, String goods_name, String goods_cover, String sell_price, String marketPrice, String goods_count, String dateline, String is_zhiying, String is_select, String pv_prices, String is_zhekou, String zhekou_number) {
        this.cartid = cartid;
        this.goods_id = goods_id;
        this.emp_id = emp_id;
        this.manager_id = manager_id;
        this.emp_name = emp_name;
        this.emp_cover = emp_cover;
        this.goods_name = goods_name;
        this.goods_cover = goods_cover;
        this.sell_price = sell_price;
        this.marketPrice = marketPrice;
        this.goods_count = goods_count;
        this.dateline = dateline;
        this.is_zhiying = is_zhiying;
        this.is_select = is_select;
        this.pv_prices = pv_prices;
        this.is_zhekou = is_zhekou;
        this.zhekou_number = zhekou_number;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getShoppingCartDao() : null;
    }

    public String getIs_zhekou() {
        return is_zhekou;
    }

    public void setIs_zhekou(String is_zhekou) {
        this.is_zhekou = is_zhekou;
    }

    public String getZhekou_number() {
        return zhekou_number;
    }

    public void setZhekou_number(String zhekou_number) {
        this.zhekou_number = zhekou_number;
    }

    /** Not-null value. */
    public String getCartid() {
        return cartid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCartid(String cartid) {
        this.cartid = cartid;
    }

    /** Not-null value. */
    public String getGoods_id() {
        return goods_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGoods_id(String goods_id) {
        this.goods_id = goods_id;
    }

    public String getEmp_id() {
        return emp_id;
    }

    public void setEmp_id(String emp_id) {
        this.emp_id = emp_id;
    }

    public String getManager_id() {
        return manager_id;
    }

    public void setManager_id(String manager_id) {
        this.manager_id = manager_id;
    }

    public String getEmp_name() {
        return emp_name;
    }

    public void setEmp_name(String emp_name) {
        this.emp_name = emp_name;
    }

    public String getEmp_cover() {
        return emp_cover;
    }

    public void setEmp_cover(String emp_cover) {
        this.emp_cover = emp_cover;
    }

    public String getGoods_name() {
        return goods_name;
    }

    public void setGoods_name(String goods_name) {
        this.goods_name = goods_name;
    }

    public String getGoods_cover() {
        return goods_cover;
    }

    public void setGoods_cover(String goods_cover) {
        this.goods_cover = goods_cover;
    }

    public String getSell_price() {
        return sell_price;
    }

    public void setSell_price(String sell_price) {
        this.sell_price = sell_price;
    }

    public String getMarketPrice() {
        return marketPrice;
    }

    public void setMarketPrice(String marketPrice) {
        this.marketPrice = marketPrice;
    }

    public String getGoods_count() {
        return goods_count;
    }

    public void setGoods_count(String goods_count) {
        this.goods_count = goods_count;
    }

    public String getDateline() {
        return dateline;
    }

    public void setDateline(String dateline) {
        this.dateline = dateline;
    }

    public String getIs_zhiying() {
        return is_zhiying;
    }

    public void setIs_zhiying(String is_zhiying) {
        this.is_zhiying = is_zhiying;
    }

    public String getIs_select() {
        return is_select;
    }

    public void setIs_select(String is_select) {
        this.is_select = is_select;
    }

    public String getPv_prices() {
        return pv_prices;
    }

    public void setPv_prices(String pv_prices) {
        this.pv_prices = pv_prices;
    }

    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
